server:
  port: 8080
  servlet:
    context-path: /auth
spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://127.0.0.1:3306/auth_service?user=kien}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${DBMS_USERNAME:kien}
    password: ${DBMS_PASSWORD:123456789}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    com.zaxxer.hikari: DEBUG
