server:
  port: 8086
spring:
  application:
    reading-service
  datasource:
    url: jdbc:mysql://localhost:3306/reading_db
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
  docker:
    compose:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 5000
service:
  chapter:
    base-url: http://localhost:8080
  comment:
    base-url: http://localhost:8083
  upload:
    base-url: http://localhost:8085
  analytics:
    base-url: http://localhost:8089
  bookmark:
    base-url: http://localhost:8084
  wishlist:
    base-url: http://localhost:8081
