server:
  port: 8086
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reading_db
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10

  docker:
    compose:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 5000

chapter:
  service:
    url: http://localhost:8080 # Hoặc tên service trong hệ thống service discovery
