server:
  port: 8099
  servlet:
    context-path: /profile

spring:
  application:
    name: user-profile-service
  neo4j:
    uri: bolt://neo4j:7687
    authentication:
      username: neo4j
      password: 123456789

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:8761/eureka/ # <<< nếu eureka cũng chạy trong Docker
  instance:
    prefer-ip-address: true
    hostname: user-profile-service
