server:
  port: 8083

spring:
  application:
    name: comment-service

  data:
    mongodb:
      host: localhost
      port: 27017
      database: comment_db

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
