server:
  port: 8083
  servlet:
    context-path: /comment

spring:
  application:
    name: comment-service

  data:
    mongodb:
      host: localhost
      port: 27017
      database: comment_db

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true