services:
  api-gateway:
    build:
      context: ./api-gateway
    container_name: gateway
    ports:
      - "8888:8888"
    networks:
      - api-network

  eureka-server:
    build:
      context: ./discovery-service
    container_name: eureka
    ports:
      - "8761:8761"
    networks:
      - api-network


  mysql-db:
    image: mysql:8.0
    container_name: frere-mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: frere_db
    ports:
      - "3307:3306"
    volumes:
      - frere_mysql_data:/var/lib/mysql
    networks:
      - api-network

  auth-service:
    build: ./auth-service
    container_name: auth
    ports:
      - "8080:8080"
    environment:
      DBMS_CONNECTION: jdbc:mysql://mysql-db:3306/frere_db
      DBMS_USERNAME: root
      DBMS_PASSWORD: 1234
    depends_on:
      - mysql-db
      - eureka-server
    networks:
      - api-network

  book-service:
    build:
      context: ./book-service
    container_name: book
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/frere_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATSOURCE_PASSWORD: 1234
    ports:
      - "8086:8086"
    networks:
      - api-network

  chapter-service:
    build:
      context: ./chapter-service
    container_name: chapter
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/frere_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    ports:
      - "8087:8087"
    networks:
      - api-network
volumes:
  frere_mysql_data:  # Đổi tên volume để phù hợp với dự án Frere
    driver: local
networks:
  api-network:
    driver: bridge

