version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_auth
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: auth_service
      MYSQL_USER: kien
      MYSQL_PASSWORD: 123456789
      MYSQL_ROOT_PASSWORD: 123456789
    networks:
      - backend

  springboot-app:
    build: .
    container_name: springboot_auth
    restart: always
    ports:
      - "8080:8080"
    environment:
      DBMS_CONNECTION: jdbc:mysql://mysql_auth:3306/auth_service?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      DBMS_USERNAME: kien
      DBMS_PASSWORD: 123456789
    depends_on:
      - mysql
    networks:
      - backend

networks:
  backend:
    driver: bridge
