server:
  port: 8888

app:
  api-prefix: /api/v1

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth:8080
          predicates:
            - Path=/api/v1/identity/**
          filters:
            - StripPrefix=2



