server:
  port: 8888

app:
  api-prefix: /api/v1

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: book-service
          uri: https://localhost:8086
          predicates:
            - Path=/reading/**
          filters:
            - StripPrefix=2