server:
  port: 8888

app:
  api-prefix: ${APP_API_PREFIX}

spring:
  application:
    name: api-gateway
  profiles:
    active: prod

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}

