server:
  port: 8099
  servlet:
    context-path: /favourite

spring:
  application:
    name: book-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/bookdb

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/