server:
  port: 8084

spring:
  application:
    name: bookmark-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/bookmark_db


  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
