version: "3.8"
services:
  chapter-service:
    build:
      context: .
    depends_on:
      - mysql-db
    networks:
      - app-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/chapter_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    ports:
      - "8087:8087"

  mysql-db:
    image: mysql:8.0
    container_name: chapter-service-mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: chapter_db
    ports:
      - "3308:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
