server:
  port: 8085
  servlet:
    context-path: /upload

spring:
  application:
    name: upload-service

  data:
    mongodb:
      uri: mongodb://mongo:27017/upload_db

cloudinary:
  cloud-name: dku1pfouk
  api-key: 368717919252533
  api-secret: taAmPM2LBVZ4oCjLjshDMkFgWjg

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: upload-service
