server:
  port: 8082
  servlet:
    context-path: /crawl

spring:
  application:
    name: crawl-service

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
  instance:
    prefer-ip-address: true
