server:
  port: 8081
  servlet:
    context-path: /recommend

spring:
  application:
    name: wishlist-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/wishlist_db


logging:
  level:
    org.wishlistservice: DEBUG
    org.springframework: INFO

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
  instance:
    prefer-ip-address: true