server:
  port: 8080
spring:
  application:
    name: chapter-service
  datasource:
    url: jdbc:mysql://localhost:3306/article
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.MySQLDialect
logging:
  level:
    org:
      springframework=DEBUG:
        eureka:
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true