server:
  port: 8087
  servlet:
    context-path: /chapter
spring:
  application:
    name: chapter-service


  data:
    mongodb:
      uri: mongodb://localhost:27017/chapterdb

logging:
  level:
    org:
      springframework: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
  instance:
    prefer-ip-address: true
