server:
  port: 8087
  servlet:
    context-path: /chapter
spring:
  application:
    name: chapter-service

  # MongoDB configuration
  data:
    mongodb:
      uri: mongodb://localhost:27017/chapterdb  # Thay đổi `localhost` và `chapterdb` theo mong muốn
  jpa:  # Nếu bạn không sử dụng JPA nữa, có thể xóa đoạn này đi.
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect  # Đoạn này có thể bỏ nếu không còn dùng MySQL

logging:
  level:
    org:
      springframework: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
  instance:
    prefer-ip-address: true
