server:
  port: 8080

spring:
  application:
    name: chapter-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: chapterdb

logging:
  level:
    org:
      springframework: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
