server:
  port: 8089

spring:
  application:
    name: Analytics-Service

  data:
    mongodb:
      uri: mongodb://mongodb:27017/analytic_db


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:8761/eureka/